[project]
name = "flask-daisy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.4",
    "flask>=3.1.2",
    "pandas>=2.3.3",
    "streamlit>=1.54.0",
]
